# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_demo1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for test_demo1
  pod 'TestFreameWork', :path => "../TestFreameWork"

  target 'test_demo1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test_demo1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
